// templates/vuejs/src/components/socket-status.vue
<script setup lang="ts">
import { useSocketIO } from "@/composables/useSocketIO";
import { useSocketIOStore } from "@/stores/socket-io";

// Header realtime indicator. Rendered only while signed in: mounting it opens the
// socket, unmounting it (sign-out) destroys it.
const { t } = useI18n();

const { ioStore } = storeToRefs(useSocketIOStore());

useSocketIO();

const label = computed(() =>
  ioStore.value.authenticated ? t("socket.connected") : t("socket.reconnecting"),
);
</script>

<template>
  <span role="status" :title="label" class="inline-flex items-center">
    <span
      :class="
        cn('size-2 rounded-full', ioStore.authenticated ? 'bg-emerald-500' : 'bg-muted-foreground')
      "
      aria-hidden="true"
    />
    <span class="sr-only">{{ label }}</span>
  </span>
</template>

// templates/nextjs/src/components/socket-status.tsx
"use client";

import { useSocketIO } from "@/hooks/useSocketIO";
import { cn } from "@/utils";
import { useTranslation } from "react-i18next";

/**
 * Realtime connection indicator. Mounting it opens the socket and unmounting it
 * destroys the socket, so render it only while signed in.
 */
export function SocketStatus() {
  const { authenticated } = useSocketIO();
  const { t } = useTranslation();

  const label = t(authenticated ? "socket.connected" : "socket.reconnecting");

  return (
    <span role="status" title={label} className="inline-flex items-center">
      <span
        aria-hidden
        className={cn(
          "size-2 rounded-full",
          authenticated ? "bg-emerald-500" : "bg-muted-foreground",
        )}
      />
      <span className="sr-only">{label}</span>
    </span>
  );
}
