// templates/tanstack-start/src/routes/login.tsx
import { useAuth, useLoginMutation } from "@/services/auth";
import { createFileRoute } from "@tanstack/react-router";
import type { FormEvent } from "react";

export const Route = createFileRoute("/login")({
  component: LoginPage,
});

/**
 * Login page — cookie-based auth. The login mutation invalidates `auth.me`, so
 * on success the session query re-resolves and we return home (the header flips
 * to Logout). No token is stored in JS; the backend sets httpOnly cookies.
 */
function LoginPage() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const login = useLoginMutation({
    onSuccess: () => navigate({ to: "/" }),
  });

  // Already signed in → no reason to show the form.
  useEffect(() => {
    if (isAuthenticated) navigate({ to: "/" });
  }, [isAuthenticated, navigate]);

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    login.mutate({ email, password });
  }

  return (
    <section>
      <h1 className="mb-4 text-3xl font-bold">{t("login.title")}</h1>

      <Card className="max-w-md">
        <form onSubmit={onSubmit} className="space-y-4">
          <div className="space-y-1">
            <label className="text-sm font-medium">{t("login.email")}</label>
            <Input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
              autoComplete="username"
            />
          </div>

          <div className="space-y-1">
            <label className="text-sm font-medium">{t("login.password")}</label>
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete="current-password"
            />
          </div>

          <Button type="submit" block disabled={login.isPending}>
            {login.isPending ? t("login.submitting") : t("login.submit")}
          </Button>

          {login.isError && <p className="text-sm text-red-600">{login.error.message}</p>}
        </form>
      </Card>
    </section>
  );
}

// templates/nuxtjs/app/pages/login.vue
<script setup lang="ts">
import { useLoginMutation, useSessionQuery } from "@/services/auth";
import { useQueryClient } from "@tanstack/vue-query";
import { ref } from "vue";

const { t } = useI18n();

// Resolve the session on the server; if already signed in, skip the form.
const queryClient = useQueryClient();
await queryClient.ensureQueryData(useSessionQuery.queryOptions());
const { data: sessionUser } = useSessionQuery();
if (sessionUser.value) await navigateTo("/");

// The login mutation invalidates `auth.me`; on success the session re-resolves and
// we return home (the header flips to Logout). No token in JS — cookie-based auth.
const {
  mutate: doLogin,
  isPending,
  error,
} = useLoginMutation({
  onSuccess: () => navigateTo("/"),
});

const email = ref("");
const password = ref("");

function onSubmit() {
  doLogin({ email: email.value, password: password.value });
}
</script>

<template>
  <section>
    <h1 class="mb-4 text-3xl font-bold">{{ t("login.title") }}</h1>

    <UiCard class="max-w-md">
      <form class="space-y-4" @submit.prevent="onSubmit">
        <div class="space-y-1">
          <label class="text-sm font-medium">{{ t("login.email") }}</label>
          <UiInput
            v-model="email"
            type="email"
            placeholder="you@example.com"
            autocomplete="username"
          />
        </div>

        <div class="space-y-1">
          <label class="text-sm font-medium">{{ t("login.password") }}</label>
          <UiInput v-model="password" type="password" autocomplete="current-password" />
        </div>

        <UiButton type="submit" block :disabled="isPending">
          {{ isPending ? t("login.submitting") : t("login.submit") }}
        </UiButton>

        <p v-if="error" class="text-sm text-red-600">{{ error.message }}</p>
      </form>
    </UiCard>
  </section>
</template>
