// templates/nuxtjs/app/pages/counter.vue
<script setup lang="ts">
import { useCounterStore } from "@/stores/counter";

const { t } = useI18n();
const counter = useCounterStore();
</script>

<template>
  <section>
    <h1 class="mb-4 text-3xl font-bold">{{ t("counter.title") }}</h1>
    <p class="mb-4 text-lg">
      {{ t("counter.count") }}: <span class="font-mono">{{ counter.count }}</span>
    </p>
    <div class="flex gap-2">
      <Button variant="secondary" size="sm" @click="counter.decrement">−</Button>
      <Button variant="secondary" size="sm" @click="counter.increment">+</Button>
      <Button variant="danger" size="sm" @click="counter.reset">Reset</Button>
    </div>
  </section>
</template>

// templates/reactjs/src/routes/counter.tsx
import { useCounterStore } from "@/stores/counter";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/counter")({
  component: CounterPage,
});

function CounterPage() {
  const { t } = useTranslation();
  const { count, increment, decrement, reset } = useCounterStore();

  return (
    <section>
      <h1 className="mb-4 text-3xl font-bold">{t("counter.title")}</h1>
      <p className="mb-4 text-lg">
        {t("counter.count")}: <span className="font-mono">{count}</span>
      </p>
      <div className="flex gap-2">
        <Button variant="secondary" size="sm" onClick={decrement}>
          −
        </Button>
        <Button variant="secondary" size="sm" onClick={increment}>
          +
        </Button>
        <Button variant="danger" size="sm" onClick={reset}>
          Reset
        </Button>
      </div>
    </section>
  );
}
